### ISSUE TITLE
Github Authorization Request

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Simon-He95/v-component-prompter#3]
Why is the extension ask for a github login?

**Comment by Simon-He95** [comment]
> Why is the extension ask for a github login?

Because this plug-in is currently only free for sponsors, you need to authorize github to determine whether it is my sponsor.

**Comment by sschneider-ihre-pvs** [comment]
oh okay, will uninstall in that case.

**Comment by Simon-He95** [comment]
Sorry to hear that
