### ISSUE TITLE
vscode内置的tsls提示问题

### ISSUE THREAD

**Issue by pzzyf** [Simon-He95/v-component-prompter#6]
何神，看你的ts提示贴图展示使用滚轮滚动提示
![image](https://github.com/Simon-He95/v-component-prompter/assets/56245609/5092f5ea-c987-4488-bdf3-26b7f5670fd9)
，vscode内置的tsls设置的是超过4个自动省略，你这边是怎么处理的
![64fe511e80f8d4b7459c9b0950a89ddd](https://github.com/Simon-He95/v-component-prompter/assets/56245609/5f45c4f6-2df9-49cd-afb3-bdbad92b83d6)

**Comment by Simon-He95** [comment]
参考`common-intellisense`吧，里面有同样的功能点
https://github.com/Simon-He95/vscode-common-intellisense/blob/main/src/ui/utils.ts#L256C18-L256C18
