### ISSUE TITLE
关于设置路径别名导致的解析失败的问题

### ISSUE THREAD

**Issue by Lirous587** [Simon-He95/v-component-prompter#7]
解决方法是在你项目的根目录下新建一个jsconfig.json文件
然后设置相应的代替符号
这里我的项目使用 ` ~ ` 来代替的 `src` ，在 ` jsconfig.json ` 中也设置相应的代替符号就可以解决这个问题了

> vite.config.js的别名设置
```js
export default defineConfig({
  resolve: {
    alias: {
      "~": path.resolve(__dirname, "src"),
    },
  },
});
```

> jsconfig.json的别名解析
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": ["./src/**/*"]
}
```

**Comment by Simon-He95** [comment]
同 https://github.com/Simon-He95/fast-jump/issues/6#issuecomment-2323228884
